# See help here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates

version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
      time: "13:38"
      # timezone: "Poland"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 10
    assignees:
      - "jiwaszki"
      - "p-wysocki"
    reviewers:
      - openvinotoolkit/openvino-configuration-mgmt
    labels:
      - "category: dependency_changes"
    # ignore:
    #   # example of ignore
    #   - dependency-name: "onnx"
    #     update-types: ["version-update:semver-patch"]
    commit-message:
      prefix: "pip"
      include: "scope"
    versioning-strategy: increase-if-necessary
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: "daily"
      time: "13:38"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 5
    assignees:
      - "ilya-lavrenov"
      - "ilyachur"
    reviewers:
      - openvinotoolkit/openvino-configuration-mgmt
    labels:
      - "category: dependency_changes"
    commit-message:
      prefix: "thirdparty"
      include: "scope"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 5
    reviewers:
      - openvinotoolkit/openvino-ci-maintainers
    labels:
      - "category: CI"
    versioning-strategy: increase-if-necessary
