# See help here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates

version: 2
updates:
  # Python API requirements
  - package-ecosystem: pip
    directory: "/src/bindings/python/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Poland"
    open-pull-requests-limit: 3
    assignees:
      - "jiwaszki"
      - "p-wysocki"
    labels:
      - "category: dependency_changes"
    versioning-strategy: increase-if-necessary

  # Model Optimizer requirements
  - package-ecosystem: pip
    directory: "/tools/mo"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 3
    assignees:
      - "rkazants"
      - "andrei-kochin"
      - "jiwaszki"
      - "p-wysocki"
    allow:
      - dependency-name: "*"
        dependency-type: "production"
    labels:
      - "category: dependency_changes"
    versioning-strategy: increase-if-necessary

  # POT requirements
  - package-ecosystem: pip
    directory: "/tools/pot"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 3
    assignees:
      - "AlexKoff88"
      - "KodiaqQ"
      - "jiwaszki"
      - "p-wysocki"
    labels:
      - "category: dependency_changes"
    versioning-strategy: increase-if-necessary

  # PaddlePaddle tests requirements
  - package-ecosystem: pip
    directory: "/src/frontends/paddle/tests/"
    schedule:
      interval: "daily"
      time: "17:40"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 3
    labels:
      - "category: dependency_changes"
    versioning-strategy: increase-if-necessary

  # Github actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 3
