# See help here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates

version: 2
updates:
  # Python API requirements
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Poland"
    open-pull-requests-limit: 300
    assignees:
      - "jiwaszki"
      - "p-wysocki"
    labels:
      - "category: dependency_changes"
    versioning-strategy: increase-if-necessary

  # Github actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 3
