# See help here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates

version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
      time: "14:07"
      # timezone: "Poland"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 14
    assignees:
      - "jiwaszki"
      - "p-wysocki"
    reviewers:
      - openvinotoolkit/openvino-configuration-mgmt
    labels:
      - "category: dependency_changes"
    allow:
      - dependency-name: "*"
        dependency-type: "production"
    commit-message:
      prefix: "pip"
      include: "scope"
    versioning-strategy: increase-if-necessary
    pull-request-branch-name:
        separator: "-"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 5
    reviewers:
      - openvinotoolkit/openvino-ci-maintainers
    assignees:
      - "ilya-lavrenov"
      - "ilyachur"
    labels:
      - "category: CI"
    pull-request-branch-name:
        separator: "-"
