name: openvino # you probably want to 'snapcraft register <name>'
version: '2022.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: OpenVINO Runtime Libraries # 79 char long summary
website: https://docs.openvino.ai/latest/index.html
description: |
  OpenVINO Runtime Libraries are used to perform inference on Intel hardware
  including CPU, GPU, GNA, MYRIAD devices
contact: sandye64@gmail.com
license: BSD-3-Clause
title: OpenVINO
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core20 # the base snap is the execution environment for this snap
type: app

architectures:
  - build-on: amd64
    run-on: amd64
assumes:
  - common-data-dir

parts:
  dependencies-part:
    plugin: nil
    build-packages:
    - wget
    - git
    - zlib1g-dev
    - pkg-config
    - libgflags-dev
    - libtbb-dev
    - mc
    stage-packages:
    - libtbb-dev
    - libgflags2.2
  cmake-build-part:
    after: [dependencies-part]
    plugin: cmake
    source: ${SNAPCRAFT_PROJECT_DIR}
    source-type: local
    # source: https://gitlab.kitware.com/cmake/cmake.git
    # source-depth: 1
    # source-tag: v3.23.1
    # source-type: git
    build-environment:
    - SNAPCRAFT_PARALLEL_BUILD_COUNT: "2"
    cmake-parameters:
    - -DCMAKE_BUILD_TYPE=Release
    # - -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
    # - -DCMAKE_C_COMPILER_LAUNCHER=ccache
    - -DBUILD_TESTS=OFF
    - -DENABLE_INTEL_GPU=OFF
    - -DENABLE_INTEL_GNA=OFF
    - -DENABLE_INTEL_CPU=OFF
    - -DENABLE_INTEL_MYRIAD=OFF
    - -DENABLE_CPPLINT=OFF
    - -DENABLE_CLANG_FORMAT=OFF
    - -DENABLE_NCC_STYLE=OFF
    - -DENABLE_CLDNN=OFF
    - -DENABLE_ONEDNN_FOR_GPU=OFF
    - -DENABLE_PROFILING_FIRST_INFERENCE=OFF
    - -DENABLE_TEMPLATE=OFF
    - -DENABLE_INTEL_MYRIAD_COMMON=OFF
    - -DENABLE_OPENCV=OFF
    - -DENABLE_OV_ONNX_FRONTEND=OFF
    - -DENABLE_OV_PADDLE_FRONTEND=OFF
    - -DENABLE_OV_TF_FRONTEND=OFF
    - -DENABLE_OV_IR_FRONTEND=OFF
    - -DENABLE_REQUIREMENTS_INSTALL=OFF
    - -DCMAKE_VERBOSE_MAKEFILE=ON
    - -DCMAKE_INSTALL_PREFIX=/usr
    - -DCPACK_GENERATOR=DEB # to disable some components like DM, install scripts, use FHS
    - -DENABLE_SAMPLES=OFF
    cmake-generator: "Unix Makefiles"
    filesets:
      exclude-dir: [-usr/share, -usr/bin/deployment_manager]
      include-dir: [usr/*]
    stage:
    - $include-dir
    - $exclude-dir

slots:
  # to share OpenVINO Runtime libraries
  openvino-2022-2-0:
    interface: content
    content: openvino-2022-2-0
    read:
      - $SNAP/usr/lib/x86_64-linux-gnu

# CONSUMER
# plugs:
#   openvino-2022-2-0:
#     interface: content
#     content: openvino-2022-2-0
#     target: $SNAP/extra-libs

apps:
  compile-tool:
    command: usr/bin/compile_tool
