name: 'Dependencies'
on: [pull_request]

jobs:
  Review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          config-file: './.github/dependency_review.yml'

  Dependabot_Approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve a PR for auto-merge
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor' }}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
