name: 'Dependency Review'
on: [pull_request]

jobs:
  Review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          config-file: './.github/dependency_review.yml'
